# Generated by Django 2.1.5 on 2019-01-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sex', models.BooleanField()),
                ('birthday', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=3)),
                ('emali', models.EmailField(max_length=254)),
                ('login_ip', models.GenericIPAddressField(default='127.0.0.1', unique=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
