# Generated by Django 2.1.5 on 2019-01-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0004_auto_20190115_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
